### ISSUE TITLE
Modèle 3D fond LED

### ISSUE THREAD

**Issue by Artelier54** [b84500/CarreRFN-DIY#1]
Modèle 3D vide sur les 2 Fond LED malgré présence de fonction et affichage en non masqué

**Comment by eziocangialosi** [comment]
Salut, c'est peut-être du à l'utilisation de la fonction "mise à l'échelle". Essaie de zoomer et dézoomer. Si besoin, je viens d'exporter en STEP les fichiers solidworks.

**Comment by eziocangialosi** [comment]
Bonjour, après vérification, les fichiers fond led sont bon mais l'angle de caméra enregistré est un peu buggé. Pour afficher la pièce il faut donc utiliser la fonction "Orientation de la vue" pour recentrer la caméra sur la pièce.

**Comment by Artelier54** [comment]
c'est bon pour moi !
